export interface RuntimeEmitterOptions {
  httpMode: "singleton" | "injected";
  hasQueryScope: boolean;
}

export function emitRuntimeFile(options: RuntimeEmitterOptions): string {
  const lines = [
    "// Auto-generated from OpenAPI spec",
    "// DO NOT EDIT - This file is automatically generated",
    "",
    `export type { HTTPFetch, HTTPFetchConfig, QueryParams } from "../../http";`,
  ];

  if (options.httpMode === "singleton") {
    lines.push(`export { httpFetch } from "../../http";`);
  }

  lines.push(`export { Routes, RouteTargets, buildRoute } from "./routes";`);

  if (options.hasQueryScope) {
    lines.push(`export type { QueryScope } from "../../query-scope";`);
    lines.push(`export { getQueryScopeKey } from "../../query-scope";`);
    lines.push(`export { queryOptions } from "@tanstack/react-query";`);
  }

  lines.push("");
  return lines.join("\n");
}
