import type { IRPath } from "../../parser/types";
import {
  renderPathParamType,
  resolvePathParamSchemas,
} from "../../utils/path-params";
import { pathToEnumName, pathToRouteValue } from "../../utils/naming";

export interface RoutesEmitterOptions {
  paths: Array<IRPath>;
  routeEnumName: string;
  stripApiPrefix?: boolean;
}

interface RouteEntry {
  enumName: string;
  routeValue: string;
  pathParamNames: Array<string>;
  pathParamSchemas: Map<string, import("../../parser/types").IRSchema>;
}

function extractPathParamNames(routePath: string): Array<string> {
  const matches = routePath.match(/\{([^}]+)\}/g) ?? [];
  return matches.map((match) => match.slice(1, -1));
}

function collectRouteEntries(options: RoutesEmitterOptions): Array<RouteEntry> {
  const seen = new Set<string>();
  const entries: Array<RouteEntry> = [];

  for (const pathItem of options.paths) {
    const enumName = pathToEnumName(pathItem.path);
    if (seen.has(enumName)) {
      continue;
    }
    seen.add(enumName);

    entries.push({
      enumName,
      pathParamNames: extractPathParamNames(pathItem.path),
      pathParamSchemas: resolvePathParamSchemas(pathItem),
      routeValue: pathToRouteValue(
        pathItem.path,
        options.stripApiPrefix === true
      ),
    });
  }

  return entries;
}

function renderRouteParamsType(entries: Array<RouteEntry>): Array<string> {
  const lines = ["export type RouteParams = {"];
  for (const entry of entries) {
    if (entry.pathParamNames.length === 0) {
      lines.push(`  ${entry.enumName}: undefined;`);
      continue;
    }

    lines.push(`  ${entry.enumName}: {`);
    for (const param of entry.pathParamNames) {
      lines.push(
        `    ${param}: ${renderPathParamType(entry.pathParamSchemas, param)};`
      );
    }
    lines.push("  };");
  }
  lines.push("};", "export type RouteKey = keyof RouteParams;", "");
  return lines;
}

export function emitRoutesFile(options: RoutesEmitterOptions): string {
  const entries = collectRouteEntries(options);
  const lines = [
    "// Auto-generated from OpenAPI spec",
    "// DO NOT EDIT - This file is automatically generated",
    "",
    "import {",
    "  buildRouteFromHandlers,",
    "  createRouteHandlers,",
    "} from \"@openmirai/openapi-codegen/routes\";",
    "",
    ...renderRouteParamsType(entries),
    `export enum ${options.routeEnumName} {`,
  ];

  for (const entry of entries) {
    lines.push(`  ${entry.enumName} = "${entry.routeValue}",`);
  }

  lines.push("}", "");
  lines.push(
    `export const Routes = createRouteHandlers<RouteParams>(${options.routeEnumName});`
  );
  lines.push(
    "export const buildRoute = buildRouteFromHandlers<RouteParams>(Routes);",
    ""
  );
  return lines.join("\n");
}

export function mergeRoutesFile(
  existingContent: string,
  newContent: string,
  routeEnumName: string,
  pathPrefix?: string
): string {
  const existingEntries = parseEnumEntries(existingContent, routeEnumName);
  const newEntries = parseEnumEntries(newContent, routeEnumName);

  if (pathPrefix !== undefined) {
    for (const [name, value] of existingEntries.entries()) {
      if (value.startsWith(pathPrefix) && !newEntries.has(name)) {
        existingEntries.delete(name);
      }
    }
  }

  const merged = new Map([...existingEntries, ...newEntries]);
  const paths = [...merged.entries()].map(([, value]) => ({
    cleanPath: value.replace(/:[^/]+/g, (match) => `{${match.slice(1)}}`),
    operations: [],
    path: value.includes(":")
      ? value.replace(/:([^/]+)/g, "{$1}")
      : value,
  }));

  return emitRoutesFile({
    paths,
    routeEnumName,
    stripApiPrefix: false,
  });
}

function parseEnumEntries(
  content: string,
  enumName: string
): Map<string, string> {
  const entries = new Map<string, string>();
  const enumStart = content.indexOf(`export enum ${enumName} {`);
  if (enumStart === -1) {
    return entries;
  }

  const enumBody = content.slice(enumStart);
  const enumEnd = enumBody.indexOf("}");
  if (enumEnd === -1) {
    return entries;
  }

  const enumContent = enumBody.slice(0, enumEnd);
  const staticRegex = /(\w+)\s*=\s*"([^"]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = staticRegex.exec(enumContent)) !== null) {
    const name = match[1];
    const value = match[2];
    if (name !== undefined && value !== undefined) {
      entries.set(name, value);
    }
  }

  return entries;
}
