import type { HttpMethod, IROperation, IRPath } from "../../parser/types";
import { relativeImportFromFunctionFile } from "../../utils/imports";
import { pathToEnumName, pathToFunctionName } from "../../utils/naming";
import {
  renderPathParamType,
  resolvePathParamSchemas,
} from "../../utils/path-params";
import {
  getFunctionTypeName,
  hasMeaningfulRequestBody,
} from "../../utils/type-names";

export interface FunctionsEmitterOptions {
  paths: Array<IRPath>;
  httpMode: "singleton" | "injected";
  hasQueryScope: boolean;
  routeEnumName: string;
  functionsDir: string;
  typesDir: string;
}

function extractPathParams(routePath: string): Array<string> {
  const matches = routePath.match(/\{([^}]+)\}/g) ?? [];
  return matches.map((match) => match.slice(1, -1));
}

function getTypeImportPath(
  cleanPath: string,
  method: HttpMethod
): string {
  const normalizedPath = cleanPath
    .replace(/\{([^}]+)\}/g, "[$1]")
    .split("/")
    .filter(Boolean)
    .join("/");
  return relativeImportFromFunctionFile(
    cleanPath,
    `types/${normalizedPath}/${method.toUpperCase()}`
  );
}

function renderOperationPathParamType(
  operation: IROperation,
  schemas: Map<string, import("../../parser/types").IRSchema>,
  param: string
): string {
  const pathParam = operation.pathParams.find((entry) => entry.name === param);
  if (pathParam !== undefined) {
    return renderPathParamType(
      new Map([[param, pathParam.schema]]),
      param
    );
  }
  return renderPathParamType(schemas, param);
}

export interface GeneratedFunctionFile {
  relativePath: string;
  content: string;
}

export function emitFunctionFiles(
  options: FunctionsEmitterOptions
): Array<GeneratedFunctionFile> {
  const files: Array<GeneratedFunctionFile> = [];

  for (const pathItem of options.paths) {
    for (const operation of pathItem.operations) {
      files.push({
        content: renderFunctionFile(pathItem, operation, options),
        relativePath: `${pathItem.cleanPath}/${operation.method.toUpperCase()}.ts`,
      });
    }
  }

  return files;
}

function renderFunctionFile(
  pathItem: IRPath,
  operation: IROperation,
  options: FunctionsEmitterOptions
): string {
  const method = operation.method;
  const functionName = pathToFunctionName(pathItem.cleanPath, method);
  const enumName = pathToEnumName(pathItem.path);
  const typeName = getFunctionTypeName(pathItem.cleanPath, method);
  const pathParams = extractPathParams(pathItem.path);
  const pathParamSchemas = resolvePathParamSchemas(pathItem);
  const propsTypeName = `${capitalize(functionName)}Props`;
  const queryOptionsPropsTypeName = `${capitalize(functionName)}QueryOptionsProps`;
  const hasRequestBody =
    method !== "get" && hasMeaningfulRequestBody(operation);
  const queryParamsPresent = operation.queryParams.length > 0;
  const typeImportPath = getTypeImportPath(pathItem.cleanPath, method);
  const runtimeImportPath = relativeImportFromFunctionFile(
    pathItem.cleanPath,
    "runtime"
  );

  const lines: Array<string> = [
    "// Auto-generated from OpenAPI spec",
    `// Path: ${method.toUpperCase()} ${pathItem.path}`,
    "// DO NOT EDIT - This file is automatically generated",
    "",
  ];

  lines.push("import type {");
  lines.push(`  ${typeName}Response,`);
  if (queryParamsPresent) {
    lines.push(`  ${typeName}Params,`);
  }
  if (hasRequestBody) {
    lines.push(`  ${typeName}Body,`);
  }
  lines.push(`} from "${typeImportPath}";`);
  lines.push("");

  if (options.httpMode === "singleton") {
    lines.push(
      `import { httpFetch, Routes, RouteTargets${options.hasQueryScope ? ", getQueryScopeKey, queryOptions" : ""} } from "${runtimeImportPath}";`
    );
  } else {
    lines.push(
      `import { Routes, RouteTargets${options.hasQueryScope ? ", getQueryScopeKey, queryOptions" : ""} } from "${runtimeImportPath}";`
    );
  }
  lines.push(
    `import type { HTTPFetch, HTTPFetchConfig${options.hasQueryScope ? ", QueryScope" : ""} } from "${runtimeImportPath}";`
  );
  lines.push("");

  lines.push(`export interface ${propsTypeName} {`);
  if (options.httpMode === "injected") {
    lines.push("  http: HTTPFetch;");
  }
  for (const param of pathParams) {
    lines.push(
      `  ${param}: ${renderOperationPathParamType(operation, pathParamSchemas, param)};`
    );
  }
  if (queryParamsPresent) {
    lines.push(`  params?: ${typeName}Params;`);
  }
  if (hasRequestBody) {
    lines.push(`  body: ${typeName}Body;`);
  }
  const configType = queryParamsPresent
    ? `Omit<HTTPFetchConfig<${typeName}Params>, "params" | "signal">`
    : 'Omit<HTTPFetchConfig, "params" | "signal">';
  lines.push(`  config?: ${configType};`);
  lines.push("  signal?: AbortSignal;");
  lines.push("}");
  lines.push("");

  if (method === "get" && options.hasQueryScope) {
    lines.push(
      `export interface ${queryOptionsPropsTypeName} extends ${propsTypeName} {`
    );
    lines.push("  queryScope: QueryScope;");
    lines.push("}");
    lines.push("");
  }

  const httpClient =
    options.httpMode === "singleton" ? "httpFetch" : "props.http";
  const destructuredProps = [
    ...(options.httpMode === "injected" ? ["http"] : []),
    ...pathParams.map((param) => param),
    ...(queryParamsPresent ? ["params"] : []),
    ...(hasRequestBody ? ["body"] : []),
    "config",
    "signal",
  ];

  lines.push(
    `export async function ${functionName}(props: ${propsTypeName}): Promise<${typeName}Response | undefined> {`
  );
  if (destructuredProps.length > 0) {
    lines.push(`  const { ${destructuredProps.join(", ")} } = props;`);
    lines.push("");
  }

  let routeCall = `Routes.${enumName}`;
  if (pathParams.length > 0) {
    routeCall = `Routes.${enumName}({ ${pathParams.map((param) => `${param}: props.${param}`).join(", ")} })`;
  }

  const fetchConfig = queryParamsPresent
    ? `{ ...config, params, signal }`
    : "{ ...config, signal }";
  const getGeneric = queryParamsPresent
    ? `<${typeName}Response, ${typeName}Params>`
    : `<${typeName}Response>`;
  const mutationGeneric = `<${typeName}Response, ${typeName}Body>`;

  switch (method) {
    case "get":
      lines.push(
        `  const { data } = await ${httpClient}.get${getGeneric}(${routeCall}, ${fetchConfig});`
      );
      break;
    case "post":
      lines.push(
        `  const { data } = await ${httpClient}.post${mutationGeneric}(${routeCall}, body, { ...config, signal });`
      );
      break;
    case "put":
      lines.push(
        `  const { data } = await ${httpClient}.put${mutationGeneric}(${routeCall}, body, { ...config, signal });`
      );
      break;
    case "patch":
      lines.push(
        `  const { data } = await ${httpClient}.patch${mutationGeneric}(${routeCall}, body, { ...config, signal });`
      );
      break;
    case "delete":
      lines.push(
        `  const { data } = await ${httpClient}.delete${getGeneric}(${routeCall}, ${fetchConfig});`
      );
      break;
  }

  lines.push("  return data;");
  lines.push("}");

  if (method === "get" && options.hasQueryScope) {
    const queryOptionsName = `${functionName}QueryOptions`;
    lines.push("");
    lines.push(
      `export function ${queryOptionsName}(props: ${queryOptionsPropsTypeName}) {`
    );
    lines.push("  const { params, queryScope } = props;");
    lines.push("  return queryOptions({");
    lines.push(
      `    queryKey: [RouteTargets.${enumName}, ...getQueryScopeKey(queryScope)${pathParams.length > 0 ? `, ${pathParams.map((param) => `props.${param}`).join(", ")}` : ""}, params],`
    );
    lines.push(
      `    queryFn: ({ signal }) => ${functionName}({ ...props, signal }).then((data) => data),`
    );
    if (pathParams.length > 0) {
      lines.push(
        `    enabled: [${pathParams.map((param) => `props.${param}`).join(", ")}].every(Boolean),`
      );
    }
    lines.push("  });");
    lines.push("}");
  }

  lines.push("");
  return lines.join("\n");
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
